In [ ]:
!pip install torch torchvision 


In [ ]:
import torch
print(torch.__version__)

1.9.0+cu102


In [ ]:
#Creating a tensor
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor= torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,device= device )
print(my_tensor)
print(device)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
cpu


In [ ]:
#Initialization methods

x= torch.empty(size= (3, 3))
print(x)
x= torch.zeros((3, 9))
print(x)


tensor([[-4.6433e-29,  3.0649e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
#initialize and convert tensors to other data types

tensor= torch.arange(4)
print(tensor)
print(tensor.short())
print(tensor.float())

tensor([0, 1, 2, 3])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0., 1., 2., 3.])


In [ ]:
#tensor to numpy array and vice versa
import numpy as np
np_array = np.zeros((5, 5))
#to convert to tensors
tensor= torch.from_numpy(np_array)


#to convert to numpy array
np_array_back= tensor.numpy()


In [ ]:
#Performing mathamatecial operations in torch

X= torch.tensor([1, 2, 3])
Y= torch.tensor([9, 8, 7])

#addition
z= X+ Y
print(z)

#divison

z= torch.true_divide(X, Y)
print(z)

#inplace operations(operation is done without making a copy)
t= torch.zeros(3)
t.add_(X)

#exponentiation

z= X.pow(2)
print(z)


#Matrix Multiplication

x1= torch.rand((2, 5))
x2= torch.rand((5, 3))
print(x1, x2)
print(torch.mm(x1, x2)) #returns  a 2X3 matrix

#Element wise multiplication

z= X* Y
print(z)

#batch matrix multiplication

batch= 32
n=10
m=20
p= 30
tensor1= torch.rand((batch, n, m))
print(tensor1)

tensor([10, 10, 10])
tensor([0.1111, 0.2500, 0.4286])
tensor([1, 4, 9])
tensor([[0.4811, 0.6190, 0.3199, 0.1224, 0.5081],
        [0.5184, 0.3397, 0.1414, 0.2568, 0.1046]]) tensor([[0.2196, 0.3121, 0.6939],
        [0.1445, 0.7185, 0.8721],
        [0.7046, 0.0467, 0.0897],
        [0.8569, 0.0194, 0.8436],
        [0.0864, 0.9065, 0.4329]])
tensor([[0.5692, 1.0729, 1.2256],
        [0.4916, 0.5122, 0.9305]])
tensor([ 9, 16, 21])
tensor([[[0.6628, 0.8848, 0.3357,  ..., 0.7894, 0.4633, 0.5369],
         [0.6964, 0.6579, 0.6123,  ..., 0.1456, 0.0642, 0.8991],
         [0.0211, 0.1317, 0.7095,  ..., 0.9087, 0.8595, 0.4484],
         ...,
         [0.2118, 0.1385, 0.4681,  ..., 0.7292, 0.9328, 0.5954],
         [0.2893, 0.6329, 0.4983,  ..., 0.6508, 0.6596, 0.7926],
         [0.6499, 0.5235, 0.3829,  ..., 0.9141, 0.6033, 0.9080]],

        [[0.5592, 0.2313, 0.3210,  ..., 0.2134, 0.1472, 0.6842],
         [0.3437, 0.8899, 0.8491,  ..., 0.7129, 0.6254, 0.9347],
         [0.0610, 0.2837, 0.98

In [ ]:
#broadcasting
#This is a matrix
x1= torch.rand((5, 5))
print(x1)
#this is a vector
x2= torch.rand((1, 5))
print(x2)
z= x1-x2
print(z)


tensor([[0.6798, 0.6891, 0.9855, 0.4446, 0.0871],
        [0.1822, 0.3108, 0.4922, 0.9359, 0.1692],
        [0.8654, 0.6702, 0.9694, 0.7974, 0.6240],
        [0.3435, 0.6397, 0.0907, 0.4582, 0.0759],
        [0.6283, 0.9227, 0.1677, 0.5531, 0.5329]])
tensor([[0.5254, 0.9239, 0.2588, 0.6854, 0.1324]])
tensor([[ 0.1544, -0.2348,  0.7267, -0.2407, -0.0453],
        [-0.3432, -0.6131,  0.2334,  0.2505,  0.0369],
        [ 0.3399, -0.2536,  0.7107,  0.1120,  0.4916],
        [-0.1819, -0.2842, -0.1681, -0.2272, -0.0565],
        [ 0.1029, -0.0012, -0.0911, -0.1322,  0.4005]])
